### ISSUE TITLE
Unicode記号を確実に入力する方法

### ISSUE THREAD

**Issue by tor-nky** [sorshi/KE-complex_modifications-NAGINATA#3]
ユニコード入力に切り替えた後、20ミリ秒待ってからユニコード、「シフト+かな」、「かな」を出力すると確実です。
「シフト+かな」を入れないとなぜか再変換になることがあります。
なおリピートは起きません。

例は、M+Comma+T で ○ (U+25CB)を出力する定義の部分です。

{"type":"basic",
    "from":{"simultaneous":[
                {"key_code":"m"},
                {"key_code":"comma"},
                {"key_code":"t"}
    ]},
    "to":[{"select_input_source":{"input_source_id":"com.apple.keylayout.UnicodeHexInput"}}],
    "parameters":{"basic.to_delayed_action_delay_milliseconds":20},
    "to_delayed_action":{"to_if_invoked":[
                {"key_code":"2","modifiers":["option"]},{"key_code":"5","modifiers":["option"]},{"key_code":"c","modifiers":["option"]},{"key_code":"b","modifiers":["option"]},{"key_code":"lang1","modifiers":["shift"]},{"key_code":"lang1"}
    ]},
    "conditions":[{"input_sources":[{"language":"ja"}],"type":"input_source_if"},
        {"input_sources":[{"input_mode_id":"Roman$"}],"type":"input_source_unless"}]
}

**Comment by sorshi** [comment]
ありがとうございます。記号が正確に入るようになったこと思います。近いうちにpushします。
