### ISSUE TITLE
ルビ入力はたまに正確に入らない

### ISSUE THREAD

**Issue by tor-nky** [sorshi/KE-complex_modifications-NAGINATA#4]
薙刀式v14のルビ入力は、
切り取り、ユニコード入力、
｜《》、2文字戻る、張り付け、1文字進む、1文字の空白を作ってクリップボードに送る、シフト+かなキー、かなキー
のように組み替えたらできました。
v11のルビ入力も、かな入力に戻すのを最後にすればいいんではないでしょうか。

**Comment by sorshi** [comment]
情報ありがとうございます。シフト+かなキー、かなキーを矢印の前に持ってきたら成功率が激下がりしてしまった感じなんでもとのまま様子を見たいと思います。
